"""June 12

Revision ID: 14af9d1c2724
Revises: None
Create Date: 2014-06-12 22:16:01.378714

"""

# revision identifiers, used by Alembic.
revision = '14af9d1c2724'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('nameindex', table_name='rest')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('nameindex', 'rest', ['tsv'], unique=False)
    ### end Alembic commands ###
