"""empty message

Revision ID: 4dcf2c077585
Revises: None
Create Date: 2014-06-03 12:00:47.412444

"""

# revision identifiers, used by Alembic.
revision = '4dcf2c077585'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rest', 'isvalid')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rest', sa.Column('isvalid', sa.BOOLEAN(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
