"""empty message

Revision ID: 12231cd7473c
Revises: aefede118b1
Create Date: 2014-04-21 20:03:40.806485

"""

# revision identifiers, used by Alembic.
revision = '12231cd7473c'
down_revision = 'aefede118b1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
