"""empty message

Revision ID: 139f4c141ae5
Revises: 12231cd7473c
Create Date: 2014-04-21 20:12:28.048768

"""

# revision identifiers, used by Alembic.
revision = '139f4c141ae5'
down_revision = '12231cd7473c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
