"""empty message

Revision ID: 15c4481f0640
Revises: 316dc1d518a1
Create Date: 2014-04-16 13:51:27.713444

"""

# revision identifiers, used by Alembic.
revision = '15c4481f0640'
down_revision = '316dc1d518a1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
