"""empty message

Revision ID: 16cb272e4c18
Revises: 27fbeccfcac5
Create Date: 2014-04-21 21:33:16.472278

"""

# revision identifiers, used by Alembic.
revision = '16cb272e4c18'
down_revision = '27fbeccfcac5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
