"""empty message

Revision ID: 17fae844b778
Revises: 3958a000dbad
Create Date: 2014-05-28 13:01:49.094929

"""

# revision identifiers, used by Alembic.
revision = '17fae844b778'
down_revision = '3958a000dbad'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
