"""empty message

Revision ID: 192f12214f35
Revises: 55b3ebac6abd
Create Date: 2014-05-16 15:55:56.099875

"""

# revision identifiers, used by Alembic.
revision = '192f12214f35'
down_revision = '55b3ebac6abd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
