"""empty message

Revision ID: 1ca8400719cd
Revises: 2d2409d2e77f
Create Date: 2014-05-09 16:21:10.832449

"""

# revision identifiers, used by Alembic.
revision = '1ca8400719cd'
down_revision = '2d2409d2e77f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
