"""empty message

Revision ID: 1edda37558da
Revises: 230b165fabf3
Create Date: 2014-05-17 10:59:41.487949

"""

# revision identifiers, used by Alembic.
revision = '1edda37558da'
down_revision = '230b165fabf3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
