"""empty message

Revision ID: 1ee46bf37496
Revises: 314c8c522e78
Create Date: 2014-04-12 14:59:19.441697

"""

# revision identifiers, used by Alembic.
revision = '1ee46bf37496'
down_revision = '314c8c522e78'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
