"""empty message

Revision ID: 1f906f9f10e8
Revises: 2a70719dd7b1
Create Date: 2014-05-22 19:36:49.229197

"""

# revision identifiers, used by Alembic.
revision = '1f906f9f10e8'
down_revision = '2a70719dd7b1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
