"""empty message

Revision ID: 2196b4fc9ac7
Revises: 441b5767765a
Create Date: 2014-05-06 21:32:33.204153

"""

# revision identifiers, used by Alembic.
revision = '2196b4fc9ac7'
down_revision = '441b5767765a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
