"""empty message

Revision ID: 230b165fabf3
Revises: 595c418f1a05
Create Date: 2014-05-17 10:50:21.432682

"""

# revision identifiers, used by Alembic.
revision = '230b165fabf3'
down_revision = '595c418f1a05'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
