"""empty message

Revision ID: 26064b56c0de
Revises: 28ea2c5887b4
Create Date: 2014-04-21 20:13:26.909601

"""

# revision identifiers, used by Alembic.
revision = '26064b56c0de'
down_revision = '28ea2c5887b4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rest', 'street')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rest', sa.Column('street', sa.VARCHAR(length=30), nullable=True))
    ### end Alembic commands ###
