"""empty message

Revision ID: 27fbeccfcac5
Revises: 26064b56c0de
Create Date: 2014-04-21 20:13:54.844195

"""

# revision identifiers, used by Alembic.
revision = '27fbeccfcac5'
down_revision = '26064b56c0de'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rest', sa.Column('street', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rest', 'street')
    ### end Alembic commands ###
