"""empty message

Revision ID: 28ea2c5887b4
Revises: 139f4c141ae5
Create Date: 2014-04-21 20:12:53.058992

"""

# revision identifiers, used by Alembic.
revision = '28ea2c5887b4'
down_revision = '139f4c141ae5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
