"""empty message

Revision ID: 2a70719dd7b1
Revises: 39fc69817643
Create Date: 2014-05-22 19:33:11.879213

"""

# revision identifiers, used by Alembic.
revision = '2a70719dd7b1'
down_revision = '39fc69817643'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
