"""empty message

Revision ID: 2aea289913fa
Revises: 2196b4fc9ac7
Create Date: 2014-05-07 13:56:11.609666

"""

# revision identifiers, used by Alembic.
revision = '2aea289913fa'
down_revision = '2196b4fc9ac7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
