"""empty message

Revision ID: 2d2409d2e77f
Revises: 38ff9194ae56
Create Date: 2014-05-09 14:42:47.830985

"""

# revision identifiers, used by Alembic.
revision = '2d2409d2e77f'
down_revision = '38ff9194ae56'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
