"""empty message

Revision ID: 314c8c522e78
Revises: 324e13352908
Create Date: 2014-04-12 09:15:20.271808

"""

# revision identifiers, used by Alembic.
revision = '314c8c522e78'
down_revision = '324e13352908'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
