"""empty message

Revision ID: 316dc1d518a1
Revises: 7f7d11d0b09
Create Date: 2014-04-16 11:42:11.735640

"""

# revision identifiers, used by Alembic.
revision = '316dc1d518a1'
down_revision = '7f7d11d0b09'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('badge', sa.Column('badgenum', sa.Integer(), nullable=True))
    op.drop_column('badge', 'Badgenum')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('badge', sa.Column('Badgenum', sa.INTEGER(), nullable=True))
    op.drop_column('badge', 'badgenum')
    ### end Alembic commands ###
