"""empty message

Revision ID: 31e849ebed42
Revises: 3e7a575da2c3
Create Date: 2014-04-21 17:26:01.024184

"""

# revision identifiers, used by Alembic.
revision = '31e849ebed42'
down_revision = '3e7a575da2c3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
