"""empty message

Revision ID: 324e13352908
Revises: b9af6ea5ab0
Create Date: 2014-04-12 09:08:45.698193

"""

# revision identifiers, used by Alembic.
revision = '324e13352908'
down_revision = 'b9af6ea5ab0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
