"""empty message

Revision ID: 33fb7323614e
Revises: 2aea289913fa
Create Date: 2014-05-07 13:57:31.357585

"""

# revision identifiers, used by Alembic.
revision = '33fb7323614e'
down_revision = '2aea289913fa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
