"""empty message

Revision ID: 35e88b7f4c34
Revises: 3f0f23a11798
Create Date: 2014-05-01 22:17:50.040905

"""

# revision identifiers, used by Alembic.
revision = '35e88b7f4c34'
down_revision = '3f0f23a11798'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
