"""empty message

Revision ID: 375943415b2f
Revises: daf90636e51
Create Date: 2014-04-21 17:27:25.827486

"""

# revision identifiers, used by Alembic.
revision = '375943415b2f'
down_revision = 'daf90636e51'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
