"""empty message

Revision ID: 38ff9194ae56
Revises: b32a95d62aa
Create Date: 2014-05-09 14:32:26.352280

"""

# revision identifiers, used by Alembic.
revision = '38ff9194ae56'
down_revision = 'b32a95d62aa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
