"""empty message

Revision ID: 3958a000dbad
Revises: 1f906f9f10e8
Create Date: 2014-05-28 12:58:24.571820

"""

# revision identifiers, used by Alembic.
revision = '3958a000dbad'
down_revision = '1f906f9f10e8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
