"""empty message

Revision ID: 39fc69817643
Revises: 49461fd0e47d
Create Date: 2014-05-22 19:29:17.296461

"""

# revision identifiers, used by Alembic.
revision = '39fc69817643'
down_revision = '49461fd0e47d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
