"""empty message

Revision ID: 3b0793229108
Revises: 17fae844b778
Create Date: 2014-05-28 13:04:25.971799

"""

# revision identifiers, used by Alembic.
revision = '3b0793229108'
down_revision = '17fae844b778'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
