"""empty message

Revision ID: 3b3872454046
Revises: 1ee46bf37496
Create Date: 2014-04-12 15:15:12.491986

"""

# revision identifiers, used by Alembic.
revision = '3b3872454046'
down_revision = '1ee46bf37496'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
