"""empty message

Revision ID: 3e7a575da2c3
Revises: 5241e8942940
Create Date: 2014-04-16 14:33:42.221515

"""

# revision identifiers, used by Alembic.
revision = '3e7a575da2c3'
down_revision = '5241e8942940'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
