"""empty message

Revision ID: 3f0f23a11798
Revises: 9e63bc207ba
Create Date: 2014-05-01 22:03:23.402348

"""

# revision identifiers, used by Alembic.
revision = '3f0f23a11798'
down_revision = '9e63bc207ba'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
