"""empty message

Revision ID: 3f8aad30b4
Revises: 192f12214f35
Create Date: 2014-05-16 23:29:26.663481

"""

# revision identifiers, used by Alembic.
revision = '3f8aad30b4'
down_revision = '192f12214f35'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
