"""empty message

Revision ID: 435fcb626e31
Revises: 4eed29c65c61
Create Date: 2014-05-09 14:06:23.748052

"""

# revision identifiers, used by Alembic.
revision = '435fcb626e31'
down_revision = '4eed29c65c61'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
