"""empty message

Revision ID: 441b5767765a
Revises: 4cac9791d8c1
Create Date: 2014-05-06 21:24:56.926315

"""

# revision identifiers, used by Alembic.
revision = '441b5767765a'
down_revision = '4cac9791d8c1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
