"""empty message

Revision ID: 49461fd0e47d
Revises: 1edda37558da
Create Date: 2014-05-17 12:00:34.529062

"""

# revision identifiers, used by Alembic.
revision = '49461fd0e47d'
down_revision = '1edda37558da'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
