"""empty message

Revision ID: 4a17538b5a3
Revises: 3b3872454046
Create Date: 2014-04-13 11:41:05.189849

"""

# revision identifiers, used by Alembic.
revision = '4a17538b5a3'
down_revision = '3b3872454046'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
