"""empty message

Revision ID: 4c67e31e4122
Revises: 772612c94fb
Create Date: 2014-05-01 21:45:52.567132

"""

# revision identifiers, used by Alembic.
revision = '4c67e31e4122'
down_revision = '772612c94fb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
