"""empty message

Revision ID: 4cac9791d8c1
Revises: 5a6a6eeef61f
Create Date: 2014-05-06 21:21:53.826951

"""

# revision identifiers, used by Alembic.
revision = '4cac9791d8c1'
down_revision = '5a6a6eeef61f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
