"""empty message

Revision ID: 4eed29c65c61
Revises: 33fb7323614e
Create Date: 2014-05-07 14:03:08.974285

"""

# revision identifiers, used by Alembic.
revision = '4eed29c65c61'
down_revision = '33fb7323614e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
