"""empty message

Revision ID: 4fe1e8a613a5
Revises: 3b0793229108
Create Date: 2014-05-28 13:29:37.375482

"""

# revision identifiers, used by Alembic.
revision = '4fe1e8a613a5'
down_revision = '3b0793229108'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rest', sa.Column('isvalid', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rest', 'isvalid')
    ### end Alembic commands ###
