"""empty message

Revision ID: 51a2630819bc
Revises: 35e88b7f4c34
Create Date: 2014-05-02 13:47:03.258363

"""

# revision identifiers, used by Alembic.
revision = '51a2630819bc'
down_revision = '35e88b7f4c34'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
