"""empty message

Revision ID: 5241e8942940
Revises: 15c4481f0640
Create Date: 2014-04-16 14:09:51.462869

"""

# revision identifiers, used by Alembic.
revision = '5241e8942940'
down_revision = '15c4481f0640'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('badge', sa.Column('badgenm', sa.String(), nullable=True))
    op.drop_column('badge', 'badgenum')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('badge', sa.Column('badgenum', sa.INTEGER(), nullable=True))
    op.drop_column('badge', 'badgenm')
    ### end Alembic commands ###
