"""empty message

Revision ID: 55b3ebac6abd
Revises: 1ca8400719cd
Create Date: 2014-05-13 20:46:01.705655

"""

# revision identifiers, used by Alembic.
revision = '55b3ebac6abd'
down_revision = '1ca8400719cd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
