"""empty message

Revision ID: 55d6f7b0e98c
Revises: 4fe1e8a613a5
Create Date: 2014-05-28 17:28:39.580563

"""

# revision identifiers, used by Alembic.
revision = '55d6f7b0e98c'
down_revision = '4fe1e8a613a5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
