"""empty message

Revision ID: 595c418f1a05
Revises: 3f8aad30b4
Create Date: 2014-05-17 10:44:13.197615

"""

# revision identifiers, used by Alembic.
revision = '595c418f1a05'
down_revision = '3f8aad30b4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
