"""empty message

Revision ID: 5a6a6eeef61f
Revises: 51a2630819bc
Create Date: 2014-05-06 20:51:23.913549

"""

# revision identifiers, used by Alembic.
revision = '5a6a6eeef61f'
down_revision = '51a2630819bc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
