"""empty message

Revision ID: 772612c94fb
Revises: 16cb272e4c18
Create Date: 2014-04-23 23:10:11.019215

"""

# revision identifiers, used by Alembic.
revision = '772612c94fb'
down_revision = '16cb272e4c18'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rest', sa.Column('lat', sa.Float(precision=6), nullable=True))
    op.add_column('rest', sa.Column('lng', sa.Float(precision=6), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rest', 'lng')
    op.drop_column('rest', 'lat')
    ### end Alembic commands ###
