"""empty message

Revision ID: 7f7d11d0b09
Revises: 4a17538b5a3
Create Date: 2014-04-16 11:25:24.537998

"""

# revision identifiers, used by Alembic.
revision = '7f7d11d0b09'
down_revision = '4a17538b5a3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('Badgenum', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('badge')
    ### end Alembic commands ###
