"""empty message

Revision ID: 9e63bc207ba
Revises: 4c67e31e4122
Create Date: 2014-05-01 21:52:55.694094

"""

# revision identifiers, used by Alembic.
revision = '9e63bc207ba'
down_revision = '4c67e31e4122'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
