"""empty message

Revision ID: aefede118b1
Revises: 375943415b2f
Create Date: 2014-04-21 17:37:01.305101

"""

# revision identifiers, used by Alembic.
revision = 'aefede118b1'
down_revision = '375943415b2f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
