"""empty message

Revision ID: b32a95d62aa
Revises: 435fcb626e31
Create Date: 2014-05-09 14:27:36.368199

"""

# revision identifiers, used by Alembic.
revision = 'b32a95d62aa'
down_revision = '435fcb626e31'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
