"""empty message

Revision ID: b9af6ea5ab0
Revises: 5277e1f1915d
Create Date: 2014-04-12 09:03:26.917359

"""

# revision identifiers, used by Alembic.
revision = 'b9af6ea5ab0'
down_revision = '5277e1f1915d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
