"""empty message

Revision ID: daf90636e51
Revises: 31e849ebed42
Create Date: 2014-04-21 17:26:46.400399

"""

# revision identifiers, used by Alembic.
revision = 'daf90636e51'
down_revision = '31e849ebed42'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
